[http]
rx_buf_size = 4096

[stack]
# tcp.num_num_connections + 3
num_sockets = 6

[tcp]
# 1 for edge worker + 2 * task concurrency
num_connections = 3
rx_buf_size = 1024
tx_buf_size = 1024
timeout = 10
