[http]
rx_buf_size = 4096

[stack]
# tcp.num_num_connections + 3
num_sockets = 6

[tcp]
# 1 for edge worker + 1 * task concurrency + 1 for log uploader
num_connections = 3
rx_buf_size = 1024
tx_buf_size = 1024
timeout = 10

[tracing]
# the number of spans which can be stored in the registry at any time
registry_store_size = 32
# the number of spans which can be active at any time
span_stack_size = 32
# the number of log events which can be buffered at any time
log_events_buffer_size = 32
