[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/riscv32imc-unknown-none-elf/debug/airflow-esp"
firmware = "target/riscv32imc-unknown-none-elf/debug/airflow-esp"

[wifi]
ssid = "Wokwi-GUEST"
password = ""
